name: TODO CD

on:
  workflow_run:
    workflows: ["TODO CI"]
    branches: ["master"]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Deploy app
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.USERNAME }}
        host: ${{ secrets.HOST }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/todo_project
          git pull origin master
          source ~/venv/bin/activate
          pip install -r requirements.txt
          python manage.py makemigrations
          python manage.py migrate
          python manage.py migrate --run-syncdb
          python manage.py check
          python manage.py runserver
          # sudo systemctl daemon-reload
          # sudo systemctl restart gunicorn
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
